algoritmo "exercicio E"

var
T,s,g,CONT : REAL
inicio
CONT<-0
s<-3
enquanto cont<=15 faca
   se(cont=0)entao
      escreval("o numero é:1")
   senao
      se(cont=1)entao
         escreval("o numero é",s)
      senao
         se(cont=2)entao
            t<-3*3
            escreval(t)
         senao
            T<-3*t
            escreval(T)
         fimse
      fimse
   fimse
   cont<-cont+1
   g<-g+1
fimenquanto



fimalgoritmo
