Algoritmo "exercicio K"

Var
C,A,R,T : real
cont,S,N : literal


Inicio
R<-0
cont<-"S"
enquanto cont= "S" faca

      escreva("insira a altura:")
      leia(A)
      escreva("insira o comprimento:")
      leia(C)
      escreva("insira o nome:")
      leia(N)
      R<- A*C
      escreva("a area total de" ,n)
      escreva("e de",r)
      escreva("deseja continuar?S/N")
      leia(cont)
      T<-R+T

fimenquanto
escreva("a area total da area residencial e de:",T)

Fimalgoritmo